# Random Forest

Classification with imbalanced data using random forest.
Comparison of accuracy score using downsampling and SMOTE upsampling

In [4]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')
## multiple outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

numerical = pd.read_csv('numerical.csv')
categorical = pd.read_csv('categorical.csv')


In [6]:
targets = pd.read_csv('target.csv')
data = pd.concat([numerical, categorical, targets], axis = 1)

In [7]:
data

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
0          0  60.000000       5        9    0         0       39        34   
1          1  46.000000       6        9   16         0       15        55   
2          1  61.611649       3        1    2         0       20        29   
3          0  70.000000       1        4    2         0       23        14   
4          0  78.000000       3        2   60         1       28         9   
...      ...        ...     ...      ...  ...       ...      ...       ...   
95407      1  61.611649       5        9    0        14       36        47   
95408      1  48.000000       7        9    1         0       31        43   
95409      1  60.000000       5        9    0         0       18        46   
95410      0  58.000000       7        9    0         0       28        35   
95411      2  80.000000       5        8    3         1       33        22   

       WWIIVETS  LOCALGOV  STATEGOV  FEDGOV  WEALTH2  POP901  POP902  POP903  \
0            18        10         2       1        5     992     264     332   
1            11         6         2       1        9    3611     940     998   
2            33         6         8       1        1    7001    2040    2669   
3            31         3         0       3        0     640     160     219   
4            53        26         3       2        9    2520     627     761   
...         ...       ...       ...     ...      ...     ...     ...     ...   
95407        11         7         8      13        9   27380    7252   10037   
95408        19         4         1       0        9    1254     322     361   
95409        20         7        23       0        9     552     131     205   
95410        20         9         1       1        7    1746     432     508   
95411        27         8        10       3        8    3935    1192    1342   

       POP90C1  POP90C2  POP90C3  POP90C4  POP90C5  ETH1  ETH2  ETH3  ETH4  \
0            0       35       65       47       53    92     1     0     0   
1           99        0        0       50       50    67     0     0    31   
2            0        2       98       49       51    96     2     0     0   
3            0        8       92       54       46    61     0     0    11   
4           99        0        0       46       54     2    98     0     0   
...        ...      ...      ...      ...      ...   ...   ...   ...   ...   
95407       99        0        0       50       50    78    10     6     4   
95408       96        0        4       51       49    91     3     0     2   
95409       99        0        0       53       47    82    14     0     1   
95410       99        0        0       47       53    92     1     1     5   
95411       99        0        0       48       52    86    12     0     1   

       ETH5  ETH6  ETH7  ETH8  ETH9  ETH10  ETH11  ETH12  ETH13  ETH14  ETH15  \
0        11     0     0     0     0      0      0      0     11      0      0   
1         6     4     2     6     4     14      0      0      2      0      1   
2         2     0     0     0     0      0      0      0      2      0      0   
3        32     6     2     0     0      0      0      0     31      0      0   
4         1     0     0     0     0      0      0      0      0      0      0   
...     ...   ...   ...   ...   ...    ...    ...    ...    ...    ...    ...   
95407     5     0     0     0     1      1      0      0      3      1      0   
95408     6     1     0     1     0      0      0      0      5      0      0   
95409     9     0     0     0     0      0      0      0      9      0      0   
95410     8     0     1     2     0      1      0      0      5      0      0   
95411     1     0     0     0     0      0      0      0      0      0      0   

       ETH16  AGE901  AGE902  AGE903  AGE904  AGE905  AGE906  AGE907  CHIL1  \
0          0      39      48      51      40      50      54      25     31   
1          4      34      41      43     

In [8]:
RAND_STATE = 42 # for reproducible shuffling
TT_RATIO = 0.25 # test/train

In [9]:
data['TARGET_B'].value_counts() # distribution of target "B" (binary label)

0    90569
1     4843
Name: TARGET_B, dtype: int64

In [10]:
# X,y
y = data['TARGET_B']
X = data.drop(['TARGET_B'], axis=1)
# split the data by type
numericalX = X.select_dtypes(np.number)
categoricalX = X.select_dtypes(np.object)

<b> Since SMOTE works on numerical data only, we encode the categorical variables

In [11]:
# onehot encoding
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='if_binary').fit(categoricalX) #  drop the first category in each feature to reduce frame size
encoded_categorical = pd.DataFrame(encoder.transform(categoricalX).toarray()) # encode
#encoded_categorical = pd.DataFrame(encoded_categorical) #
X = pd.concat([numericalX, encoded_categorical], axis = 1) # rejoin
X.head(3)


TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
0      0  60.000000       5        9    0         0       39        34   
1      1  46.000000       6        9   16         0       15        55   
2      1  61.611649       3        1    2         0       20        29   

   WWIIVETS  LOCALGOV  STATEGOV  FEDGOV  WEALTH2  POP901  POP902  POP903  \
0        18        10         2       1        5     992     264     332   
1        11         6         2       1        9    3611     940     998   
2        33         6         8       1        1    7001    2040    2669   

   POP90C1  POP90C2  POP90C3  POP90C4  POP90C5  ETH1  ETH2  ETH3  ETH4  ETH5  \
0        0       35       65       47       53    92     1     0     0    11   
1       99        0        0       50       50    67     0     0    31     6   
2        0        2       98       49       51    96     2     0     0     2   

   ETH6  ETH7  ETH8  ETH9  ETH10  ETH11  ETH12  ETH13  ETH14  ETH15  ETH16  \
0     0     0     0     0      0      0      0     11      0      0      0   
1     4     2     6     4     14      0      0      2      0      1      4   
2     0     0     0     0      0      0      0      2      0      0      0   

   AGE901  AGE902  AGE903  AGE904  AGE905  AGE906  AGE907  CHIL1  CHIL2  \
0      39      48      51      40      50      54      25     31     42   
1      34      41      43      32      42      45      32     33     46   
2      35      43      46      37      45      49      23     35     40   

   CHIL3  AGEC1  AGEC2  AGEC3  AGEC4  AGEC5  AGEC6  AGEC7  CHILC1  CHILC2  \
0     27     11     14     18     17     13     11     15      12      11   
1     21     13     14     33     23     10      4      2      11      16   
2     25     13     20     19     16     13     10      8      15      14   

   CHILC3  CHILC4  CHILC5  HHAGE1  HHAGE2  HHAGE3  HHN1  HHN2  HHN3  HHN4  \
0      34      25      18      26      10      23    18    33    49    28   
1      36      22      15      12       1       5     4    21    75    55   
2      30      22      19      25      10      23    21    35    44    22   

   HHN5  HHN6  MARR1  MARR2  MARR3  MARR4  HHP1  HHP2  DW1  DW2  DW3  DW4  \
0    12     4     61      7     12     19   198   276   97   95    2    2   
1    23     9     69      4      3     24   317   360   99   99    0    0   
2     6     2     63      9      9     19   183   254   69   69    1    6   

   DW5  DW6  DW7  DW8  DW9   HV1   HV2  HV3  HV4  HU1  HU2  HU3  HU4  HU5  \
0    0    0    7    7    0   479   635    3    2   86   14   96    4    7   
1    0    0    0    0    0  5468  5218   12   10   96    4   97    3    9   
2    5    3    3    3    0   497   546    2    1   78   22   93    7   18   

   HHD1  HHD2  HHD3  HHD4  HHD5  HHD6  HHD7  HHD8  HHD9  HHD10  HHD11  HHD12  \
0    38    80    70    32    84    16     6     2     5      9     15      3   
1    59    94    88    55    95     5     4     1     3      5      4      2   
2    36    76    65    30    86    14     7     2     5     11     17      3   

   ETHC1  ETHC2  ETHC3  ETHC4  ETHC5  ETHC6  HVP1  HVP2  HVP3  HVP4  HVP5  \
0     17     50     25      0      0      0     2     7    13    27    47   
1     18     44      5      0      0      0    97    98    98    98    99   
2     17     60     18      0      1      0     0     1     6    18    50   

   HVP6  HUR1  HUR2  RHP1  RHP2  RHP3  RHP4  HUPA1  HUPA2  HUPA3  HUPA4  \
0     0     1    61    58    61    15     4      2      0      0     14   
1    94     0    83    76    73    21     5      0      0      0      4   
2     0     4    36    49    51    14     5      4      2     24     11   

   HUPA5  HUPA6  HUPA7  RP1  RP2  RP3  RP4     MSA    ADI    DMA   IC1   IC2  \
0      1      0      0    2    5   17   73     0.0  177.0  682.0   307   318   
1      0      0      0   91   91   91   94  4480.0   13.0  803.0  1088  1096   
2      2      3      6    0    2    9   44     0.0  281.0  

In [12]:
# check for missing values
X.isna().any(axis=1).value_counts()
X.isna().any(axis=1).value_counts()

False    95410
True         2
dtype: int64

False    95410
True         2
dtype: int64

In [13]:
# remove the null values
na_idx = X[X.isna().any(axis=1)].index
X = pd.DataFrame(X).drop(na_idx)
y = pd.DataFrame(y).drop(na_idx)

In [14]:
# test-train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TT_RATIO, random_state=RAND_STATE)

X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

y_train_regression = X_train['TARGET_D']
y_test_regression = X_test['TARGET_D']

# Now we can remove the column target d from the set of features
X_train = X_train.drop(['TARGET_D'], axis = 1)
X_test = X_test.drop(['TARGET_D'], axis = 1)

In [41]:
X_train.columns = X_train.columns.astype(str)

In [40]:
X_test.columns = X_test.columns.astype(str)

In [33]:
def down_samp_rand(Xin, yin, ratio=1):
        from imblearn.under_sampling import RandomUnderSampler
        """Downsamples majority class using random sampling.
        Ratio argument is the ratio of minority class to the downsampled majority
        """
        rus = RandomUnderSampler(sampling_strategy=ratio, random_state=RAND_STATE)
        X_rus, y_rus = rus.fit_resample(Xin, yin)
        return X_rus, y_rus

In [34]:
X_train, y_train = down_samp_rand(X_train,y_train)

In [35]:
# check that we have downsampled
y_train.value_counts()

TARGET_B
0           3673
1           3673
dtype: int64

#### train, fit, and evaluate model

In [36]:
from sklearn.ensemble import RandomForestClassifier
#the hyperparametres 
rfc_ops = {"max_depth":6,
           "min_samples_leaf":20,
           "n_estimators":100,#no of trees
           "bootstrap":True,
           "oob_score":True, #out of the bag, bagging score. functions as a test mechanism like cf
           "random_state":RAND_STATE} #cap letter variables by convention refer to constants

clf = RandomForestClassifier(**rfc_ops)

        #max_depth=6,min_samples_leaf=20,max_features=None,n_estimators=100,
         #                    bootstrap=True,oob_score=True, random_state=RAND_STATE)
clf.fit(X_train, y_train)
print("train prediction accuracy score: %.2f" %(clf.score(X_train, y_train)))
print("test prediction accuracy score: %.2f"  %(clf.score(X_test, y_test)))

RandomForestClassifier(max_depth=6, min_samples_leaf=20, oob_score=True,
                       random_state=42)

train prediction accuracy score: 0.67
test prediction accuracy score: 0.61


In [37]:
from sklearn.metrics import accuracy_score
score_ds = accuracy_score(y_test,clf.predict(X_test))

In [39]:
score_ds

0.6052907391103844

Reference: [Details](https://scikit-learn.org/stable/modules/model_evaluation.html#accuracy-score) about how the accuracy is computed

#### cross validation

In [49]:
from sklearn.model_selection import cross_val_score
folds=5
cross_val_scores = cross_val_score(clf, X_train, y_train, cv=folds)


In [50]:
print("cv scores over {:d} iterations: \n".format(folds))
cross_val_scores

cv scores over 5 iterations: 



array([0.60068027, 0.60721579, 0.57658271, 0.59836624, 0.57317903])

In [51]:
print("the std. dev. in the cv scores is {:.4f}".format(np.std(cross_val_scores)))

the std. dev. in the cv scores is 0.0137


## Random forest model using SMOTE upsampling

In [52]:
# test-train refresh
X.columns = X.columns.astype(str) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TT_RATIO, random_state=RAND_STATE)

X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

y_train_regression = X_train['TARGET_D']
y_test_regression = X_test['TARGET_D']

# Now we can remove the column target d from the set of features
X_train = X_train.drop(['TARGET_D'], axis=1)
X_test = X_test.drop(['TARGET_D'],   axis=1)


In [53]:
# again we need to drop the null (we use the same shuffling)
na_idx = X_train[X_train.isna().any(axis=1)].index
X_train = pd.DataFrame(X_train).drop(na_idx)
y_train = pd.DataFrame(y_train).drop(na_idx)

In [54]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train, y_train = smote.fit_resample(X_train, y_train)
y_train.value_counts()

TARGET_B
0           67884
1           67884
dtype: int64

In [55]:
# fit the model and evaluate using the upsampled data from SMOTE
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=20, oob_score=True,
                       random_state=42)

In [56]:
print("test prediction accuracy score: %.2f" %(clf.score(X_test, y_test)))


test prediction accuracy score: 0.88


In [57]:
score_us = accuracy_score(y_test,clf.predict(X_test))

In [58]:
pd.DataFrame({"score": [score_ds,score_us]},index=["downsampled", "upsampled"] )

score
downsampled  0.605291
upsampled    0.876410

Note the improvement using S:MOTE over downsmpling

In [59]:
clf.predict_proba(X_test)

array([[0.76718277, 0.23281723],
       [0.66365442, 0.33634558],
       [0.46221738, 0.53778262],
       ...,
       [0.66223795, 0.33776205],
       [0.6612932 , 0.3387068 ],
       [0.70575164, 0.29424836]])

In [60]:
clf.predict(X_test)

array([0, 0, 1, ..., 0, 0, 0])